#- hosts: all
#  tasks:
#  - name: "include_role: opensuse_microos"
#    include_role:
#      name: opensuse_microos_fancy_server
#    when: "ansible_distribution == 'openSUSE MicroOS'"

- hosts: qemu_vd
  tasks:
  - name: "include_role: opensuse_microos_qemu_vd"
    include_role:
      name: opensuse_microos_qemu_vd
    when: "ansible_distribution == 'openSUSE MicroOS'"

- hosts: iscsi_target
  tasks:
  - name: "include_role: opensuse_microos_iscsi_target_server"
    include_role:
      name: opensuse_microos_iscsi_target_server
    when: "ansible_distribution == 'openSUSE MicroOS'"

