#- hosts: all
#  tasks:
#  - name: "include_role: opensuse_microos"
#    include_role:
#      name: opensuse_microos_fancy_server
#    when: "ansible_distribution == 'openSUSE MicroOS'"

- hosts: qemu_vd
  roles:
    - opensuse_microos_qemu_vd

- hosts: iscsi_target
  roles:
    - opensuse_microos_iscsi_target_server

- hosts: nfs_server
  roles:
    - opensuse_microos_nfs_server

- hosts: podman_server
  roles:
    - opensuse_microos_podman_server
    - podman_container_host

